{
 "title": "ETL Overview",
 "tags": [
  "etl",
  "postgres",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Postgres Exporter UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"postgres\"}",
     "legendFormat": "postgres exporter"
    }
   ]
  },
  {
   "title": "TPS (commits+rollbacks) – 5m rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"payments\"}[5m]) + rate(pg_stat_database_xact_rollback{datname=\"payments\"}[5m])",
     "legendFormat": "TPS"
    }
   ]
  },
  {
   "title": "TPS histórico – 5m rate",
   "type": "timeSeries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit{datname=\"payments\"}[5m])",
     "legendFormat": "commit"
    },
    {
     "expr": "rate(pg_stat_database_xact_rollback{datname=\"payments\"}[5m])",
     "legendFormat": "rollback"
    }
   ]
  },
  {
   "title": "Connections (payments)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{datname=\"payments\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Buffers Read vs Hit",
   "type": "timeSeries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_blks_read{datname=\"payments\"}[5m])",
     "legendFormat": "blks_read"
    },
    {
     "expr": "rate(pg_stat_database_blks_hit{datname=\"payments\"}[5m])",
     "legendFormat": "blks_hit"
    }
   ]
  }
 ]
}